### ISSUE TITLE
Checking the entered credentials. 

### ISSUE THREAD

**Issue by Progluver** [yezz123/Phisher#10]
The current version gives us anything that is entered by the target. It may be valid or wrong. So what if we add the feature to check if the entered username and password are valid and then give us the output?

What are the limitations we will be facing while working on this feature ?

**Comment by yezz123** [comment]
It's gonna be a great idea for Creating a checker of information that  Target(s) entered Buts its gonna be with the same page that when we run `Ngrok` the checker gonna run also.
- If you have a template or a diagram how is that gonna work the checker and the phish page in the same time welcome..... This gonna be amazing

**Comment by Progluver** [comment]
I am planning to work on this part of the project with python. Cause i have almost no knowledge about php and just started learning it. I got the very basics of it and working on it. I don't know what limitations we will be having while doing this. But i will keep updating the ideas i get and my work in this section. Maybe with your help we can make this work @yezz123 .

**Comment by yezz123** [comment]
@Progluver This gonna be a great idea to work with python, i guess its gonna add a great addon.
But the problem is how we can launch it with the same `.html` file and add a checker inside it, i guess if we want to make it great its better to work with `.JavaScript` and that gonna be launch it with the same file and work better.

**Comment by adnane-X-tebbaa** [comment]
ydke fih hhhhhhhhhhhhhhhhhhh
